  $ dune build --display short @install
      ocamldep alib/.alib.objs/alib.ml.d
      ocamldep alib/.alib.objs/main.ml.d
      ocamldep blib/.blib.objs/blib.ml.d
      ocamldep blib/sub/.sub.objs/sub.ml.d
        ocamlc blib/sub/.sub.objs/.byte_objs/sub.{cmi,cmo,cmt}
        ocamlc blib/sub/sub.cma
        ocamlc alib/.alib.objs/.byte_objs/alib__.{cmi,cmo,cmt}
      ocamlopt alib/.alib.objs/.native_objs/alib__.{cmx,o}
      ocamlopt blib/sub/.sub.objs/.native_objs/sub.{cmx,o}
      ocamlopt blib/sub/sub.{a,cmxa}
      ocamlopt blib/sub/sub.cmxs
        ocamlc blib/.blib.objs/.byte_objs/blib.{cmi,cmo,cmt}
        ocamlc blib/blib.cma
      ocamlopt blib/.blib.objs/.native_objs/blib.{cmx,o}
      ocamlopt blib/blib.{a,cmxa}
      ocamlopt blib/blib.cmxs
        ocamlc alib/.alib.objs/.byte_objs/alib.{cmi,cmo,cmt}
      ocamlopt alib/.alib.objs/.native_objs/alib.{cmx,o}
        ocamlc alib/.alib.objs/.byte_objs/alib__Main.{cmi,cmo,cmt}
        ocamlc alib/alib.cma
      ocamlopt alib/.alib.objs/.native_objs/alib__Main.{cmx,o}
      ocamlopt alib/alib.{a,cmxa}
      ocamlopt alib/alib.cmxs
